
export const metadata = {
  title: 'My react and next app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>Welcome in my contact page{children}</body>
    </html>
  )
}
